# Generated by Django 5.0.7 on 2024-07-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=255)),
                ('cost_per_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('norm_time_per_month', models.IntegerField()),
                ('total_working_time', models.IntegerField(editable=False)),
                ('total_salary_fund', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.positiondirectory')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.tariffdirectory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1), ('quantity__lte', 1000)), name='quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.CheckConstraint(check=models.Q(('norm_time_per_month__gte', 1), ('norm_time_per_month__lte', 744)), name='norm_time_per_month_range'),
        ),
    ]
