# Generated by Django 5.0.7 on 2024-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0002_positiondirectory_tariffdirectory_staffschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffschedule',
            name='norm_time_per_month_range',
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.CheckConstraint(check=models.Q(('norm_time_per_month__gte', 1), ('norm_time_per_month__lte', 44000)), name='norm_time_per_month_range'),
        ),
    ]
