# Generated by Django 5.0.7 on 2024-07-11 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0003_remove_staffschedule_norm_time_per_month_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
