# Generated by Django 5.0.7 on 2024-07-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0006_historicaltariffdirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerPositionDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
