# Generated by Django 5.0.7 on 2024-07-15 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0007_organizerpositiondirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('base', models.TextField()),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.organizerpositiondirectory')),
            ],
        ),
    ]
