# Generated by Django 5.0.7 on 2024-07-15 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0011_historicaltaxsystem_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsystem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalTaxSystem',
        ),
    ]
