# Generated by Django 5.0.7 on 2024-07-15 09:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0013_historicaltaxsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.TextField(blank=True)),
                ('contract_price', models.IntegerField()),
                ('contract_number_date', models.TextField(blank=True)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('activity_types', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('postal_address', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tax_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.taxsystem')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.TextField(blank=True)),
                ('contract_price', models.IntegerField()),
                ('contract_number_date', models.TextField(blank=True)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('activity_types', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('postal_address', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax_system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Accounting_button.taxsystem')),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
