# Generated by Django 5.0.7 on 2024-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0017_historicalorganizertariff_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nomenclature_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='nomenclature_units',
            field=models.IntegerField(default=0),
        ),
    ]
