# Generated by Django 5.0.7 on 2024-07-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0019_worktypegroup_historicalworktypegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworktypegroup',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='worktypegroup',
            name='author_name',
        ),
        migrations.AddField(
            model_name='historicalworktypegroup',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktypegroup',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
