# Generated by Django 5.0.7 on 2024-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0020_remove_historicalworktypegroup_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworktypegroup',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='worktypegroup',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='historicalworktypegroup',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worktypegroup',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
