# Generated by Django 5.0.7 on 2024-07-17 07:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0021_rename_comment_historicalworktypegroup_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_norm', models.IntegerField()),
                ('tariff_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField(blank=True)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tariff_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Accounting_button.tariffdirectory')),
                ('work_type_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Accounting_button.worktypegroup')),
            ],
            options={
                'verbose_name': 'historical work type',
                'verbose_name_plural': 'historical work types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_norm', models.IntegerField()),
                ('tariff_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField(blank=True)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tariff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktypes', to='Accounting_button.tariffdirectory')),
                ('work_type_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktypegroup')),
            ],
        ),
    ]
