# Generated by Django 5.0.7 on 2024-07-19 02:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0022_historicalworktype_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworktype',
            name='tariff_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='tariff_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='StandardOperationsJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(editable=False, max_length=100)),
                ('client_display', models.CharField(editable=False, max_length=100)),
                ('group', models.CharField(editable=False, max_length=100)),
                ('work_type', models.CharField(editable=False, max_length=100)),
                ('work_type_display', models.CharField(editable=False, max_length=100)),
                ('time_norm', models.PositiveIntegerField(editable=False)),
                ('tariff', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_time', models.PositiveIntegerField(editable=False)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('change_history', models.TextField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client')),
            ],
        ),
    ]
