# Generated by Django 5.0.7 on 2024-07-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0023_alter_historicalworktype_tariff_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktype'),
        ),
    ]
