# Generated by Django 5.0.7 on 2024-07-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0024_alter_standardoperationsjournal_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='author_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='client_display',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='group',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='work_type_display',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
