# Generated by Django 5.0.7 on 2024-07-19 03:54

import Accounting_button.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0025_alter_standardoperationsjournal_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='quantity',
            field=models.IntegerField(default=1, validators=[Accounting_button.models.validate_quantity]),
        ),
    ]
