# Generated by Django 5.0.7 on 2024-07-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0026_alter_standardoperationsjournal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='total_time',
            field=models.IntegerField(editable=False),
        ),
    ]
