# Generated by Django 5.0.7 on 2024-07-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0027_alter_standardoperationsjournal_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.worktype'),
        ),
    ]
