# Generated by Django 5.0.7 on 2024-07-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0028_alter_standardoperationsjournal_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.client'),
        ),
    ]
