# Generated by Django 5.0.7 on 2024-07-23 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0029_alter_standardoperationsjournal_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationsjournal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.worktypegroup'),
        ),
    ]
